address validation issues concerning ettercap.desktop
$ desktop-file-validate ettercap.desktop

warning: value "ettercap.xpm" for key "Icon" in group "Desktop Entry"
 is an icon name with an extension, but there should be no extension
 as described in the Icon Theme Specification if the value is not an
 absolute path

warning: value "Application;Network;System;Security;GTK;" for key
 "Categories" in group "Desktop Entry" contains a deprecated value
 "Application"

error: value "Application;Network;System;Security;GTK" for string list
 key "Categories" in group "Desktop Entry" does not have a semicolon
 (';') as trailing character